In [1]:
import numpy as np

#### Let the network structure be [2,3,2];

### `Code for First Layer`

In [2]:
input_layer_1 = np.array([[1,2]])

weight_layer_1 = np.array([[0.5,0.2],[0.9,.6],[0.3,0.55]])
weight_layer_1 = weight_layer_1.transpose()

bias_layer_1 = np.array([[1],[2],[3]])


In [3]:
output_layer_1 = np.dot(input_layer_1,weight_layer_1) + bias_layer_1.transpose()
output_layer_1

array([[1.9, 4.1, 4.4]])

### `Code for Second Layer`

In [4]:
input_layer_2 = output_layer_1

weight_layer_2 = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6]])
weight_layer_2 = weight_layer_2.transpose()

bias_layer_2 = np.array([[4],[5]])

In [5]:
output_layer_2 = np.dot(input_layer_2,weight_layer_2) + bias_layer_2.transpose()
output_layer_2

array([[ 6.33, 10.45]])

### `Defining Activation Functions`

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the ReLU function
def relu(x):
    return np.maximum(0, x)

### `Output`

In [7]:
sigmoid_output = sigmoid(output_layer_2)
sigmoid_output

array([[0.99822114, 0.99997105]])

In [8]:
reLU_output = relu(output_layer_2)
reLU_output

array([[ 6.33, 10.45]])